
CREATE TABLE "ElementosInfoBasica"(
	"Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Numero Atomico" INTEGER NULL,
	"Simbolo" TEXT NULL,
	"Nombre" TEXT NULL,
	"Peso Atomico" REAL NULL,
	"Periodo" INTEGER NULL,
	"Fase" TEXT NULL,
	"Estructura Cristalina" TEXT NULL,
	"Color" TEXT NULL,
	"Valencia" INTEGER NULL,
	"Numeros de Oxidacion" TEXT NULL,
	"Configuracion Electronica Abreviada" TEXT NULL,
	"Configuracion Electronica" TEXT NULL,
	"Caracteristicas" TEXT NULL,
	"Punto de Fusion" TEXT NULL,
	"Punto de Ebullicion" TEXT NULL,
	"Resumen" TEXT NULL) 

CREATE TABLE "ElementosInfoDetalle"(
	"Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Numero Atomico" INTEGER NULL,
	"Isotopos Estables" TEXT NULL,
	"Tipo Electrico" TEXT NULL,
	"Radiactivo" TEXT NULL,
	"Abundancia en la corteza terrestre (%)" TEXT NULL,
	"Descubrimiento" TEXT NULL,
	"Descubierto por" TEXT NULL,
	"Angulos de Red" TEXT NULL,
	"Vida Media" TEXT NULL,
	"Modulo Compresibilidad (Bulk)" TEXT NULL,
	"Dureza Brinell" TEXT NULL,
	"Presion Critica" TEXT NULL,
	"Temperatura Critica" TEXT NULL,
	"Conductividad Electrica" TEXT NULL,
	"Densidad (kg/m3)" REAL NULL,
	"Radio Covalente" TEXT NULL,
	"Afinidad Electronica" TEXT NULL,
	"Punto de Curie" TEXT NULL,
	"Modo de Decaimiento" TEXT NULL,
	"Electronegatividad" REAL NULL,
	"Densidad Liquida" TEXT NULL,
	"Constante de Red" TEXT NULL,
	"Multiplicidad Atomica del Gas" TEXT NULL,
	"Calor de Fusion" TEXT NULL,
	"Calor de Vaporizacion" TEXT NULL,
	"Tipo Magnetico" TEXT NULL,
	"Susceptibilidad Magnetica" TEXT NULL,
	"Volumen Molar" REAL NULL,
	"Radio de Poisson" TEXT NULL,
	"Numeros Cuanticos" TEXT NULL,
	"Indice Refractivo" REAL NULL,
	"Resistividad" TEXT NULL,
	"Conductividad Termica" TEXT NULL,
	"Punto de Superconductividad" TEXT NULL,
	"Expansion Termica" TEXT NULL,
	"Velocidad del sonido en el elemento" TEXT NULL,
	"Numero de Grupos Espaciales" REAL NULL,
	"Nombre del Grupo Espacial" TEXT NULL,
	"Radio de Van Der Waals" TEXT NULL,
	"Radio atomico en Angstroms" REAL NULL,
	"Radio covalente (Å)" REAL NULL,
	"Radio de Van der Waals (Å)" REAL NULL,
	"Modulo de Young" TEXT NULL,
	"Nombres alotropicos" TEXT NULL,
	"Energias de Ionizacion" TEXT NULL) 


CREATE TABLE "Isotopos"(
	"Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Numero Atomico" INTEGER NULL,
	"Numero Correlativo" INTEGER NULL,
	"Isotopo" INTEGER NULL,
	"Numero de masa" INTEGER NULL,
	"Masa Atomica Relativa" TEXT NULL,
	"Composicion Isotopica" TEXT NULL,
	"Peso Atomico Estandar" TEXT NULL) 


CREATE TABLE "ValidaElementos"(
	"Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Numero" INTEGER NULL,
	"Simbolo" TEXT NULL,
	"Nombre" TEXT NULL,
	"Electrones" INTEGER NULL,
	"Protones" INTEGER NULL,
	"Neutrones" INTEGER NULL)

