INSERT INTO "moleculas_lista" VALUES (1,'H2O','monóxido de dihidrógeno','óxido de hidrógeno','Agua');
INSERT INTO "moleculas_lista" VALUES (2,'CO','Monóxido de carbono','Óxido de carbono (II)','Oxido de Carbono');
INSERT INTO "moleculas_lista" VALUES (3,'K2O','Monóxido de dipotasio','Óxido de potasio','óxido potásico');
INSERT INTO "moleculas_lista" VALUES (4,'Cu2O','Monóxido de dicobre','Óxido de cobre (I)','Óxido cuproso');
INSERT INTO "moleculas_lista" VALUES (5,'Fe2O3','Trióxido de dihierro','Óxido de hierro (III)','Óxido ferrico');
INSERT INTO "moleculas_lista" VALUES (6,'FeO','Monoxido de hierro','Óxido de hierro (II)','Oxido ferroso');
INSERT INTO "moleculas_lista" VALUES (7,'SiO2','Dióxido de silicio','Óxido de silicio (IV)','Oxido de Silicio');
INSERT INTO "moleculas_lista" VALUES (8,'KH','monohidruro de potasi','Hidruro de potasio','hidruro potásico');
INSERT INTO "moleculas_lista" VALUES (9,'NiH3','Trihidruro de níquel','Hidruro de níquel (III)','hidruro niquélico');
INSERT INTO "moleculas_lista" VALUES (10,'CuH2','Dihidruro de cobre','Hidruro de cobre (II)','hidruro cúprico');
INSERT INTO "moleculas_lista" VALUES (11,'PbH4','Tetrahidruro de plomo','Hidruro de plomo (IV)','hidruro plúmbico');
INSERT INTO "moleculas_lista" VALUES (12,'FeS','Monosulfuro de hierro','Sulfuro de hierro (II)','sulfuro ferroso');
INSERT INTO "moleculas_lista" VALUES (13,'Fe2S3','Trisulfuro de dihierro','Sulfuro de hierro (III)','sulfuro ferrico');
INSERT INTO "moleculas_lista" VALUES (14,'AuCl3','Tricloruro de oro','Cloruro de oro (III)','cloruro áurico');
INSERT INTO "moleculas_lista" VALUES (15,'AuBr','Monobromuro de oro','Bromuro de oro (I)','bromuro auroso');
INSERT INTO "moleculas_lista" VALUES (16,'MnS2','Disulfuro de manganeso','Sulfuro de manganeso (IV)','Sulfuro de manganeso');
INSERT INTO "moleculas_lista" VALUES (17,'N2O','Monoxido de dinitrógeno','Óxido de nitrógeno (I)','Oxido Hiponitroso');
INSERT INTO "moleculas_lista" VALUES (18,'N2O3','Trióxido de dinitrógeno','Óxido de nitrógeno (III)','Oxido Nitroso');
INSERT INTO "moleculas_lista" VALUES (19,'N2O5','Pentóxido de dinitrógeno','Óxido de nitrógeno (V)','Oxido Nitrico');
INSERT INTO "moleculas_lista" VALUES (20,'HIO','Monoxoyodato (I) de hidrógeno','Ácido monoxoyódico (I)','ácido hipoyodoso');
