INSERT INTO "quiz_question" VALUES(1,"¿Cuál es la fórmula del agua?",TRUE);
INSERT INTO "quiz_question" VALUES(2,"¿Cuál es la fórmula del Óxido ferroso?",TRUE);
INSERT INTO "quiz_question" VALUES(3,"¿Cuál es la fórmula del Óxido férrico?",TRUE);
INSERT INTO "quiz_question" VALUES(4,"¿Cuál es la fórmula del Óxido Nitroso?",TRUE);
INSERT INTO "quiz_question" VALUES(5,"¿Cuál es la fórmula del Dióxido de Carbono?",TRUE);
INSERT INTO "quiz_question" VALUES(6,"¿Cuál es la fórmula del Óxido de Aluminio?",TRUE);
INSERT INTO "quiz_question" VALUES(7,"¿Cuál es la fórmula del Óxido HipoIodoso?",TRUE);
INSERT INTO "quiz_question" VALUES(8,"¿Cuál es la fórmula del Óxido Iodoso?",TRUE);
INSERT INTO "quiz_question" VALUES(9,"¿Cuál es la fórmula del Óxido Iodico?",TRUE);
INSERT INTO "quiz_question" VALUES(10,"¿Cuál es la fórmula del Óxido PerIodico?",TRUE);
INSERT INTO "quiz_question" VALUES(11,"Escriba la formula del agua",FALSE);
INSERT INTO "quiz_question" VALUES(12,"Escriba la formula del Óxido ferroso",FALSE);
INSERT INTO "quiz_question" VALUES(13,"Escriba la formula del Óxido férrico",FALSE);
INSERT INTO "quiz_question" VALUES(14,"Escriba la formula del Óxido Nitroso",FALSE);
INSERT INTO "quiz_question" VALUES(15,"Escriba la fórmula del Dióxido de Carbono",FALSE);
INSERT INTO "quiz_question" VALUES(16,"Escriba la fórmula del Óxido de Aluminio",FALSE);
INSERT INTO "quiz_question" VALUES(17,"Escriba la fórmula del Óxido HipoIodoso",FALSE);
INSERT INTO "quiz_question" VALUES(18,"Escriba la fórmula del Óxido Iodoso",FALSE);
INSERT INTO "quiz_question" VALUES(19,"Escriba la fórmula del Óxido Iodico",FALSE);
INSERT INTO "quiz_question" VALUES(20,"Escriba la fórmula del Óxido PerIodico",FALSE);